add architecture C4 diagrams
tzaretskaya/architecture-sprint-3 pull request #1
Opened 2024-12-15 01:44 UTC by tzaretskaya

2024-12-21 17:05 UTC, dchekushin requested changes

2024-12-21 17:05 UTC, dchekushin commented on smart-home-monolith/docs/Container.puml
> +
Выдели мобильное приложение / веб-сайт отдельным контейнером - User и Administrator используют их.
Укажи протоколы, технологии взаимодействия, например http, между системами.

2024-12-21 17:05 UTC, dchekushin commented on smart-home-monolith/docs/Container.puml
> +System_Ext(partnernApi, "Partner N API", "API for device management and monitoring")
На диаграмме достаточно обозначить одну систему.

2024-12-21 17:05 UTC, dchekushin commented on smart-home-monolith/docs/Container.puml
> +System_Ext(partnernQueueClient, "Partner N Queue Client", "Publish sensor events")
Обычно устройства и датчики имеют внутренние механизмы отправки сообщение. Отдельной очереди не требуется. Partner API может отправлять данные в 'Device Partners Integrations'

2024-12-21 17:05 UTC, dchekushin commented on Project_template_part_1.md
Добавь еще несколько доменов. В требованиях к системе указано, что пользователь самостоятельно настраивает сценарии работы и просматривает телеметрию.

2024-12-21 17:05 UTC, dchekushin commented on smart-home-monolith/docs/Container.puml
> +Container_Boundary(SmartHomeSystem, "Smart home System") {
На диаграмме не хватает сервисов которые реализуют требование - пользователи самостоятельно настраивает сценарии работы и просматривают телеметрию.

2024-12-21 17:05 UTC, dchekushin commented on smart-home-monolith/docs/ER.puml
> +
Продумай как в новой системе будет храниться телеметрия (значения показателей различных модулей).

2024-12-30 16:32 UTC, tzaretskaya commented on Project_template_part_1.md
Это задание касается же только изначального, монолитного, проекта, а не целевого. В нем нет никаких сценариев. По поводу телеметрии: есть же мониторинг -- это же оно и есть

2024-12-30 16:33 UTC, tzaretskaya commented on Project_template_part_1.md
@dchekushin

2024-12-30 16:34 UTC, tzaretskaya commented on smart-home-monolith/docs/Container.puml
> +Container_Boundary(SmartHomeSystem, "Smart home System") {
@dchekushin  Все хранится в сервисе DeviceApp. На более детальной диаграмме это видно

2024-12-30 16:45 UTC, tzaretskaya commented on smart-home-monolith/docs/ER.puml
> +
@dchekushin У устройства есть поле Status, а также есть json params, в котором может лежать в нужном виде набор значений для данного типа устройства

2025-01-09 07:41 UTC, merged